### ISSUE TITLE
Migrate to django viewflow.fsm

### ISSUE THREAD

**Issue by Vyko** [jazzband/django-fsm-log#187]
django-fsm is no longer maintained and was archived on 9 April 2023.
It now lives in viewflow

**Comment by Vyko** [comment]
Actually, viewflow already implement a logging mechanism https://docs.viewflow.io/fsm/models.html#logging

**Comment by lorenzomorandini** [comment]
Viewflow is a totally different package, it's not possible to migrate to it (I think).

[Here](https://github.com/jazzband/django-fsm-log/issues/188) the discussion to migrate to django-fsm-2 which will be mantained.
