### ISSUE TITLE
Support FSMIntegerField in StateLogInline

### ISSUE THREAD

**Issue by florianm** [jazzband/django-fsm-log#70]
Using StateLogInline, I noticed that a FSMIntegerField renders the underlying (integer) database value, which carries no business meaning. 
It would be very useful if StateLogInline could render FSMIntegerFields as their display value!

**Comment by blueyed** [comment]
Is this fixed / addressed by 0cabedc?  (unreleased)

**Comment by achillis2** [comment]
I also noticed this today. Can this be fixed in the version 4.0.0? Thanks

**Comment by ticosax** [comment]
It's normally released since v1.6.0
