### ISSUE TITLE
New maintainers wanted

### ISSUE THREAD

**Issue by tysonclugg** [jazzband/django-fsm-log#96]
For various reasons, new maintainers are sought for django-fsm-log. Candidates should post a comment here supporting their appointment, and I'll grant ownership of the repo once suitable candidates are found.

I'd like to take this opportunity to thank @ticosax for his numerous contributions over the last 2½ years. Every contribution whether comment, critique, or pull request is appreciated (but especially the pull requests). @ticosax has given more than his fair share of each, and for this I say thankyou.

On with the show... who's up next?

**Comment by josh-stableprice** [comment]
Maybe take a look at hosting it under the Jazzband org, so that whoever is invested can join - https://jazzband.co/

**Comment by ticosax** [comment]
I support that, jazzband is probably the way to go.

**Comment by tysonclugg** [comment]
Personal experience with Jazzband has me somewhat concerned:

1. Author attribution using standard git means is not highly valued in the Jazzband community.  Aside from morale issues that arise when author names are squashed our of the commit log, this leads to long term code provenance issues making copyright difficult to enforce.

2. Arbitration is performed by the "roadies", but sadly this amounts to only a single person, with no path for further appeal on any decision.

I won't rule out a move to Jazzband, but I can ask for due consideration of my concerns before the move is made.  @ticosax?

**Comment by josh-stableprice** [comment]
Interesting to know. I personally dislike squashing, but not for the reason you've detailed above. I haven't ever thought about copyright issues inside an open source library such as this before. 
Are you concerned about the project getting claims of using stolen code or about people being denied attribution and getting salty about it?

I'm sure there are systems for dealing with no. 2, although I'm not sure if Jazzband introduces this issue any more than just not being a main contributor does.

**Comment by tysonclugg** [comment]
@josh-stableprice Are you stepping forward as a maintainer?

See https://github.com/jazzband/django-ddp for an example of a project that moved to Jazzband but stagnated due to lack of maintainers.  Someone still has to take control.

**Comment by josh-stableprice** [comment]
I do currently use this package and I am somewhat invested in it continuing to work correctly so I would be interested. I do notice that there are some long running forks of this package that may be able to be persuaded to come back upstream and assist with maintenance.

**Comment by dbinetti** [comment]
gladly!  although I must say I'm more of a cargo-culter than an actual
programmer...

**Comment by tysonclugg** [comment]
Thanks to @josh-stableprice and @dbinetti for stepping forward to maintain `django-fsm-log`.  :+1: 

I'm also putting out the call to all people who have up to date forks as shown on the [django-fsm-log network graph](https://github.com/gizmag/django-fsm-log/network):

- @cwuebbels 
- @cw-intellineers 
- @imomaliev 
- @bjorntheart 

Pending further responses within the next week, I'll transfer ownership and move the repo to whichever location is deemed most suitable by the new maintainer team.

Sorry for the delayed response, I've been sick with Influenza A [like many others near me](https://www.theage.com.au/national/victoria/influenza-claims-the-lives-of-50-victorians-as-national-toll-hits-231-20190706-p524py.html).

**Comment by imomaliev** [comment]
@tysonclugg I step forward as maintainer and could help with this project

**Comment by imomaliev** [comment]
@tysonclugg Hi, what is the status on this?

**Comment by hartwork** [comment]
django-fsm-log is blocking an upgrade to Python 3 (#98) so it would be great to see this ball rolling again. Any news?

**Comment by imomaliev** [comment]
Mb we should move this project in @jazzband ?

**Comment by MRigal** [comment]
@tysonclugg any news on that? I vote in favor of adding @imomaliev who has the pending PR https://github.com/gizmag/django-fsm-log/pull/95 since now 2 years which fixes some very basics issues.

It's a pity you started the process and let it die out...

**Comment by ticosax** [comment]
Given the history on this conversation, it looks like I can take actions and initiate a transfer to jazzband.
I'll add it to my todo list.

**Comment by ticosax** [comment]
I'll cut a the new release 3.0.0 first.

**Comment by ticosax** [comment]
We are on jazzband

**Comment by hartwork** [comment]
@ticosax thanks for the release and the transition!

**Comment by imomaliev** [comment]
Great news. Thanks to everyone.
